ccflags-y += -Idrivers/sensors/laser_focus/laser_library/inc
ccflags-y += -Idrivers/sensors/laser_focus/laser_HEPTAGON/inc

obj-y += HPTG_interface.o
obj-y += HPTG_i2c.o
obj-y += HPTG_factory_func.o
obj-y += HPTG_shipping_func.o
obj-y += HPTG_debug.o
obj-y += msm_laser_focus_hepta.o
