ccflags-y += -Idrivers/sensors/laser_focus/laser_library/inc
ccflags-y += -Idrivers/sensors/laser_focus/laser_HEPTAGON/inc

obj-y += msm_laser_focus.o
obj-y += laser_verify.o
obj-y += laser_timer.o
obj-y += laser_sysfs.o
obj-y += laser_procfs.o
obj-y += laser_parser.o 
obj-y += laser_mutex.o
obj-y += laser_log.o
obj-y += laser_gpio.o
obj-y += laser_debug.o
obj-y += laser_focus_i2c.o










